version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Ruby Version
        VARIANT: "2.7"
        # Node Version: 10, 11, ...
        NODE_VERSION: "lts/*"

    env_file:
      - '.env.docker'

    volumes:
      - ..:/workspace:cached
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  db:
    image: postgres:10
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app

  redis:
    image: redis

volumes:
  postgres-data:
